### ISSUE TITLE
yardım

### ISSUE THREAD

**Issue by beyzade0028** [basicodemine/Millionaire#1]
hocam iyi günler. ben türkçe öğretmeniyim. bu oyunu akıllı tahtalara uyarlayıp kullanma ihtimalimiz var mı?
bana yardımcı olur musun? oyunun build edilmemiş hali var mı elinde? yada soruları değiştirip kullanabiliyor muyuz? yardımcı olursan çok sevinirim

**Comment by basicodemine** [comment]
/egemen.ozogul ==> FB
@basicodemine ==> TW
